### ISSUE TITLE
cinatra will not download from your git url

### ISSUE THREAD

**Issue by Kingsbu** [axx/cpp-web-dev#1]
Hi Alex
Thank you for creating the container
I thought i should let you know that when i pulled your repository
the container failed to build because git does not download cinatra from your git url

I know doing documentation sucks .. but do mind giving a detailed example of using this container

**Comment by axx** [comment]
Hello,
Actually I created this repo in the context of an article that I wrote : “Web app development with Modern C++ (part 1)” by Allister Sanchez https://link.medium.com/555jgGHCJW.
Could you try if you can make it work by following the steps in the article? I'll try incorporate it into this repository later.
Cheers, 
Allister

**Comment by Kingsbu** [comment]
Hi Alex i did get the container to run.
I am busy learning docker and always wanted to mess around with feather
but do to lack or documentation and enough back ground in c++ i could not figure
how to build web-pages to run on this framework

**Comment by axx** [comment]
I've updated the README with links to my sample web app (cpp-web-app) that was the result of the tutorial article. Thanks again for raising this issue.
As for improving your C++ background, I suggest you go straight to learning C++ based on the 2017 standard which is the one used in cinatra.
