### ISSUE TITLE
Docker files

### ISSUE THREAD

**Issue by opakaj** [axx/cpp-web-dev#2]
So I'm slightly perplexed. There are three docker files according to your medium article. Please explain the directories to place them in as well as their names. Because inget an error message claiming there is no such file as Dockerfile build because I call it docker file simply.

**Comment by axx** [comment]
> So I'm slightly perplexed. There are three docker files according to your medium article. Please explain the directories to place them in as well as their names. Because inget an error message claiming there is no such file as Dockerfile build because I call it docker file simply.

Hello, @opakaj . Sorry if it wasn't obvious. To answer your question, we indeed have 3 docker files coming from 2 repositories:
1. cpp-web-dev/Dockerfile (which I referred to as Dockerfile.build in my article). Its purpose is to generate the Docker image of our C++ development environment, where we will compile the actual C++ application.
2.  cpp-web-dev/Dockerfile.lean. Its purpose is to generate a Docker image of our C++ runtime environment. As you can see, it only contains the Boost runtime libraries on top of a basic Ubuntu Linux container. We don't need the development packages (e.g. cmake) in our runtime environment.
3. cpp-web-app/Dockerfile.  Its purpose is to use the Docker images produced by the two above-mentioned Dockerfiles to produce a Docker image that you can execute anywhere.

Of course this could probably be done with a single Dockerfile but I wanted to have a reusable "development environment image" that could be used in multiple web apps.

As for the directories to place them, you can simply put the two repositories in separate folders, like so:
```bash
cd /somewhere/you/want
git clone https://github.com/axx/cpp-web-dev.git
git clone https://github.com/axx/cpp-web-app.git
```
Then to build your own versions the dev Docker images:
```bash
cd /somewhere/you/want/cpp-web-dev
docker build -t opakaj/cpp-web-dev:build-1.0.0 -f Dockerfile .
docker build -t opakaj/cpp-web-dev:lean-1.0.0 -f Dockerfile.lean .
```
To build your own web-app version using your own dev Docker images, you need to edit `cpp-web-app/Dockerfile`, replacing `allister` by `opakaj`, then do:
```bash
cd /somewhere/you/want/cpp-web-app
docker build -t opakaj/cpp-web-app:latest .
docker run opakaj/cpp-web-app:latest
```

I hope this helps :)
